### ISSUE TITLE
Nothing is happening when I run the image

### ISSUE THREAD

**Issue by the-lazy-fox** [h1f0x/rtorrent-flood-openvpn#13]
Hi,
I'm running the image with the following docker-compose file on my Synology NAS DS916+ but nothing is happening. No logs and config file remains empty.
Any ideas?

```
version: "2.3"
services: 
 rtorrent-flood-openvpn:
    container_name: seeding-extra-tmp
    image: h1f0x/rtorrent-flood-openvpn:latest
    restart: unless-stopped
    ports:
      - 50000:50000
      - 33370:80
    environment:
     - PUID=1026
     - PGID=100
     - TZ=Europe/Paris
    volumes:
     - /volume1/docker/seeding/config:/config
     - /volumeUSB1/usbshare1-2:/output/complete:ro
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    security_opt:
      - label:disable
```

**Comment by poespas** [comment]
When switching over to docker compose I ran into the same issue, I was able to fix it with the following docker compose yml:
```
version: "3.8"

services:
  torrent:
    image: h1f0x/rtorrent-flood-openvpn:latest
    privileged: true
    network_mode: bridge
    volumes:
      - /output:/output
      - /flood:/config
    stdin_open: true
    tty: true
```
