### ISSUE TITLE
Flood doesn't delete data

### ISSUE THREAD

**Issue by Tawagot0** [h1f0x/rtorrent-flood-openvpn#4]
When I delete a torrent via flood, the data is still present in the download folder.

Docker compose:
```
  flood:
    image: h1f0x/rtorrent-flood-openvpn
    container_name: flood
    restart: always
    tty: true
    privileged: true
    networks:
      external:
        ipv4_address: 172.20.0.10
    volumes:
      - /mnt/downloads/torrents/:/downloads
      - /opt/flood/config:/config
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
    labels:
      - traefik.port=80
      - traefik.frontend.rule=Host:flood.${DOMAIN},www.flood.${DOMAIN}
      - traefik.backend=Flood
```

I have change the path in rtorrent.rc:
```
## Instance layout (base paths)
method.insert = cfg.basedir,  private|const|string, (cat,"/config/")
method.insert = cfg.download, private|const|string, (cat,"/downloads/")
```
The response when i delete a torrent:
![flood](https://i.imgur.com/nRzpvzP.png)

access.log in `/var/log/nginx/`

![access](https://i.imgur.com/gnoyumN.png)

But the deleted data is still in the folder `/downloads`
